import type { ExerciseVideo } from "@/lib/types";

export const exerciseCatalog: ExerciseVideo[] = [
  {
    id: "shoulder-roll-4",
    title: "Shoulder Roll",
    description: "Gentle shoulder circles to loosen the upper body after desk work.",
    videoUrl: "https://example.com/videos/shoulder-roll-4",
    thumbnailUrl: "https://example.com/thumbnails/shoulder-roll-4.jpg",
    bodyArea: "upper-body",
    purpose: "mobility",
    durationMinutes: 4,
    intensity: "medium",
  },
  {
    id: "hip-mobility-6",
    title: "Hip Mobility Flow",
    description: "A standing sequence for opening the hips and waking up the lower body.",
    videoUrl: "https://example.com/videos/hip-mobility-6",
    thumbnailUrl: "https://example.com/thumbnails/hip-mobility-6.jpg",
    bodyArea: "lower-body",
    purpose: "mobility",
    durationMinutes: 6,
    intensity: "high",
  },
  {
    id: "seated-calf-raise-5",
    title: "Seated Calf Raise",
    description: "A seated circulation drill that is easy to fit into low-energy days.",
    videoUrl: "https://example.com/videos/seated-calf-raise-5",
    thumbnailUrl: "https://example.com/thumbnails/seated-calf-raise-5.jpg",
    bodyArea: "lower-body",
    purpose: "recovery",
    durationMinutes: 5,
    intensity: "low",
  },
  {
    id: "neck-mobility-5",
    title: "Neck Mobility Reset",
    description: "Slow neck mobility work to release tension and improve comfort.",
    videoUrl: "https://example.com/videos/neck-mobility-5",
    thumbnailUrl: "https://example.com/thumbnails/neck-mobility-5.jpg",
    bodyArea: "upper-body",
    purpose: "mobility",
    durationMinutes: 5,
    intensity: "low",
  },
  {
    id: "breathing-reset-3",
    title: "Breathing Reset",
    description: "Three minutes of guided breathing to downshift and recover focus.",
    videoUrl: "https://example.com/videos/breathing-reset-3",
    thumbnailUrl: "https://example.com/thumbnails/breathing-reset-3.jpg",
    bodyArea: "core",
    purpose: "recovery",
    durationMinutes: 3,
    intensity: "low",
  },
  {
    id: "walk-in-place-10",
    title: "Walk in Place",
    description: "An indoor walking break that raises energy without needing equipment.",
    videoUrl: "https://example.com/videos/walk-in-place-10",
    thumbnailUrl: "https://example.com/thumbnails/walk-in-place-10.jpg",
    bodyArea: "full-body",
    purpose: "cardio",
    durationMinutes: 10,
    intensity: "medium",
  },
];
